ktor:
    application:
        modules:
            - com.nexusaquarium.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/nexus_aquarium_db}
  user: ${POSTGRES_USER:admin}
  password: ${POSTGRES_PASSWORD:admin}