ktor:
    application:
        modules:
            - com.nexusaquarium.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/nexus_aquarium_db"
  user: admin
  password: admin