services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus-postgres
    environment:
      POSTGRES_DB: nexus_aquarium_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"  # Puerto 5433 para evitar conflicto con tu PostgreSQL existente
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nexus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d nexus_aquarium_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  nexus-aquarium-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nexus-aquarium-api:local  # Tag the built image
    container_name: nexus-aquarium-api
    ports:
      - "4301:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/nexus_aquarium_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nexus-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nexus-network:
    driver: bridge
