version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nexus-network
    restart: unless-stopped
    healthcheck: # <<< MEJORA: Verifica que la BD esté lista para aceptar conexiones
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nexus-aquarium-api:
    image: gaboiv/nexus-aquarium-api:latest
    container_name: nexus-aquarium-api
    ports:
      - "${API_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nexus-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nexus-network:
    driver: bridge